name: buildsampleshmg

on:
  push

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Load Harbour
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34-0703.yml
         workflow_conclusion: success
         name: hb34-0703
         path: c:\temp

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         md c:\temp\harbour
         7z x -y c:\temp\hb34-0703.7z -oc:\temp\harbour


    - name: Load Source Code
      run: |
         c:
         git clone http://github.com/JoseQuintas/testall c:\temp\harbour\addons --recurse --depth 1

    - name: Build
      env:
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw64\bin
      run: |
         c:
         cd \temp\harbour\addons
         hbmk2 testallhmg.hbp -w3 -es2 -m -n -q
