name: Build Harbour binaries for Windows 32 MSVC

on:
  push:
    paths: 
      - '.github/workflows/harbour_win32_msvc22.yml'

jobs:
  build:
    runs-on: windows-latest
    
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Move HMG's Harbour folder
      shell: cmd
      run: |
        move harbour oldharbour

    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Build Harbour Core
      shell: cmd
      run: |
        cd harbour
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_CONTRIBS=
        set HB_COMPILER=msvc
        win-make.exe

    - name: Build HMG
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
        SET HMGPATH=%~dp0
        SET PATH=%HMGPATH%\harbour\bin\win\msvc;%PATH%
        NewBuildAll.bat 

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
       name: harbour_win32_msvc
       path: harbour
