name: hb32-pack-1002

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.2 mingw 10.2 hmg hmge hwgui oohg'
        default: 'hb32-pack-1002'
        required: true

jobs:

  BuildLibs:
    runs-on: windows-latest
    steps:

    - name: Load Harbour
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb32-1002.yml
         workflow_conclusion: success
         name: hb32-1002
         path: c:\temp
         repo: JoseQuintas/hbpack

    - name: Unzip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp
         md \temp\harbour
         cd \temp\harbour
         7z x -y c:\temp\hb32-1002.7z -oc:\temp\harbour

    - name: Load Source Code
      run: |
         c:
         git clone http://github.com/JoseQuintas/testall c:\temp\harbour\addons --recurse --depth 1

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\.gitmodules

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\hmg\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmg\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmg\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmg\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmg\workflows

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmge\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmge\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmge\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hmge\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hwgui\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hwgui\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hwgui\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\hwgui\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\.gitmodules

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\distros\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\distros\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\distros\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\distros\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\doc\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\doc\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\doc\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\doc\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\fmt\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\fmt\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\fmt\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\fmt\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\ide\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\ide\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\ide\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\ide\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\samples\.git

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\samples\.gitattributes

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\samples\.github

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\samples\.gitignore

    - name: Clean
      uses: JoseQuintas/action-rm@v1.0.2
      with:
         path: c:\temp\harbour\addons\oohg\samples\.gitmodules

    - name: Build HMG,HMGE,HWGUI,OOHG 32 bits
      env:
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw32\bin
      run: |
         c:
         cd \temp\harbour\addons\hmg
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw
         cd \temp\harbour\addons\hmge
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw
         cd \temp\harbour\addons\hwgui\hwgui
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw
         cd \temp\harbour\addons\oohg
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw

    - name: Build HMG,HMGE,HWGUI,OOHG 64 bits
      env:
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw64\bin
      run: |
         c:
         cd \temp\harbour\addons\hmg
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw64
         cd \temp\harbour\addons\hmge
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw64
         cd \temp\harbour\addons\hwgui\hwgui
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw64
         cd \temp\harbour\addons\oohg
         hbmk2 *.hbp -workdir=c:\temp -comp=mingw64

    - name: Zip HMG, HMGE, HWGUI, OHG
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp\harbour
         7z a -r c:\temp\hb32-pack-1002.7z c:\temp\harbour\

    - name: Save HMG, HMGE, HWGUI, OOHG
      uses: actions/upload-artifact@v2
      with:
         name: hb32_pack_1002
         path: c:\temp\hb32-pack-1002.7z
