#
# use:    JoseQuintas/harbour_32/hb32_1002
# create: hmg_hb32_mingw_1002
#

name: HMG Harbour 3.2 mingw 10.2 32/64 bits

on:
  push:
  schedule:
   - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.4 mingw 7.3'
        default: 'hmg_hb32_mingw_1002'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Load Mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb32_1002.yml
         workflow_conclusion: success
         name: hb32_1002
         path: c:\temp
         repo: JoseQuintas/harbour_32

    - name: Unzip
      run: |
         c:
         dir c:\temp
         md c:\temp\harbour
         7z x -y c:\temp\hb32_1002.7z -oc:\temp\harbour

    - name: Install Source Code
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         md \temp\harbour\addons
         git clone https://github.com/$env:repo c:\temp\harbour\addons\hmg\ --depth 10

    - name: Build 32 bits
      env:
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw32\bin
         HBMK_CMD: -q -rebuild -workdir=c:\temp
      run: |
         c:
         cd c:\temp\harbour\addons\hmg
         copy test\hbmk.hbc \temp\harbour\bin
         c:buildlib.bat

#    - name: Build 64 bits
#      env:
#         HB_COMPILER: mingw64
#         HB_INSTALL_PREFIX: c:\temp\harbour
#         PATH: c:\temp\harbour\comp\mingw64\bin
#      run: |
#         c:
#         cd \temp\harbour\addons\hmg
#         c:buildlib.bat

# msvc
# call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp\harbour
         7z a -r c:\temp\hmg_hb32_mingw_1002.7z c:\temp\harbour\addons\hmg\*.*

# big size, temporary removed harbour 3.2 and mingw 10.2
#         7z a -r c:\temp\hmg_hb32_mingw_1002.7z c:\temp\harbour\*.*

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: hmg_hb32_mingw_1002
         path: c:\temp\hmg_hb32_mingw_1002.7z

    - name: TestAll
      env:
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw32\bin
         HBMK_CMD: -q -rebuild -workdir=c:\temp
      run: |
         c:
         cd c:\temp\harbour\addons\hmg\test
         hbmk2 testall.hbp -q -workdir=c:\temp
